function buildGenericPointLayerConfig(table, options = {}) {
  return {
    table: `sde.${table}`,
    idColumn: 'objectid',
    idStrategy: 'manual',
    geometry: {
      enabled: true,
      type: 'Point',
      column: options.geometryColumn || 'shape',
      readColumn: options.readColumn || options.geometryColumn || 'shape',
      xField: 'xcoord',
      yField: 'ycoord'
    },
    insertFields: options.fields || ['assetid', 'sttncode', 'sttnname', 'constituncy', 'division', 'railway'],
    updateFields: options.fields || ['assetid', 'sttncode', 'sttnname', 'constituncy', 'division', 'railway'],
    searchableFields: options.searchableFields || ['assetid', 'sttncode', 'sttnname']
  };
}

function buildBridgeLikePointLayerConfig(table, numberField) {
  const fields = [
    'gid',
    'asset_id',
    'assetid',
    numberField,
    'bridgeno',
    'distkm',
    'distm',
    'latitude',
    'longitude',
    'xcoord',
    'ycoord',
    'railway',
    'division',
    'state',
    'district',
    'tmssection',
    'bridgetype',
    'spanconf',
    'constituncy',
    'constituency',
    'attachment_bundle_url'
  ];

  return buildGenericPointLayerConfig(table, {
    fields,
    geometryColumn: 'geom',
    readColumn: 'geom',
    searchableFields: ['asset_id', 'assetid', numberField, 'bridgeno', 'state', 'district']
  });
}

function buildLevelXingLayerConfig() {
  const fields = [
    'gid',
    'distkm',
    'distm',
    'latitude',
    'longitude',
    'fdetail',
    'stnfrom',
    'line',
    'railway',
    'division',
    'ersection',
    'tmssection',
    'state',
    'district',
    'city',
    'asset_id',
    'xcoord',
    'ycoord',
    'remark',
    'date',
    'stnto',
    'gisid',
    'tahsil',
    'village',
    'valid',
    'user_type',
    'unit_type',
    'unit_code',
    'unit_name',
    'department',
    'user_id',
    'expired_flag',
    'created_by',
    'created_date',
    'modified_by',
    'modified_date',
    'mapped_flag',
    'mapped_id',
    'remark2',
    'makerdet',
    'checkerdet',
    'approverdet',
    'lxingno',
    'tvu',
    'lxingtype',
    'sent_by',
    'globalid',
    'constituncy',
    'attachment_bundle_url'
  ];

  return buildGenericPointLayerConfig('levelxing', {
    fields,
    geometryColumn: 'shape',
    readColumn: 'shape',
    searchableFields: ['asset_id', 'lxingno', 'stnfrom', 'stnto', 'state', 'district', 'division'],
    draftWorkflow: {
      table: 'sde.levelxing_edit',
      editIdColumn: 'edit_id',
      originalIdColumn: 'original_id',
      statusColumn: 'status',
      checkerColumn: null,
      approverColumn: null,
      originalStatusValue: 'Under Editing',
      draftStatusValue: 'Sent to Checker'
    }
  });
}

function buildGenericPolygonLayerConfig(table, options = {}) {
  return {
    table: `sde.${table}`,
    idColumn: 'objectid',
    idStrategy: 'manual',
    draftWorkflow: options.draftWorkflow,
    geometry: {
      enabled: false,
      type: 'Polygon',
      column: options.geometryColumn || 'shape',
      readColumn: options.readColumn || options.geometryColumn || 'shape'
    },
    insertFields: options.fields || ['distfromkm', 'distfromm', 'disttokm', 'disttom', 'railway', 'division'],
    updateFields: options.fields || ['distfromkm', 'distfromm', 'disttokm', 'disttom', 'railway', 'division'],
    searchableFields: options.searchableFields || ['distfromkm', 'disttokm', 'division']
  };
}

function buildLandPlanOnTrackLayerConfig() {
  const fields = [
    'distfromkm',
    'distfromm',
    'disttokm',
    'disttom',
    'railway',
    'division',
    'state',
    'district',
    'constituncy',
    'imageno',
  ];

  return buildGenericPolygonLayerConfig('land_plan_on_track', {
    fields,
    geometryColumn: 'shape',
    readColumn: 'shape',
    searchableFields: ['distfromkm', 'disttokm', 'state', 'district', 'constituncy', 'division']
  });
}

module.exports = {
  station: {
    table: 'sde.station',
    idColumn: 'objectid',
    idStrategy: 'manual', // manual MAX()+1 for now
    draftWorkflow: {
      table: 'sde.station_edit',
      editIdColumn: 'edit_id',
      originalIdColumn: 'original_id',
      statusColumn: 'status',
      checkerColumn: 'checkerdet',
      approverColumn: 'approverdet',
      originalStatusValue: 'Under Editing',
      draftStatusValue: 'Sent to Checker'
    },
    validation: {
      table: 'sde.station_1_code',
      idColumn: 'objectid',
      idStrategy: 'manual',
      insertFields: [
        'station_code',
        'station_valid_from',
        'station_valid_upto',
        'station_name',
        'zone_code',
        'division_code',
        'category'
      ]
    },

    geometry: {
      enabled: true,
      type: 'Point',
      column: 'shape',
      xField: 'xcoord',
      yField: 'ycoord'
    },

    insertFields: [
      'sttncode',
      'sttnname',
      'sttntype',
      'distkm',
      'distm',
      'state',
      'district',
      'constituncy',
      'latitude',
      'longitude',
      'xcoord',
      'ycoord',
      'railway',
      'category',
      'attachment_bundle_url'
    ],

    updateFields: [
      'distkm',
      'distm',
      'state',
      'district',
      'constituncy',
      'sttnname',
      'category',
      'sttntype',
      'attachment_bundle_url'
    ],

    searchableFields: [
      'sttncode',
      'state',
      'district'
    ]
  },
  bridge_start: {
    table: 'sde.bridge_start',
    idColumn: 'objectid',
    idStrategy: 'manual',
    draftWorkflow: {
      table: 'sde.bridge_start_edit',
      editIdColumn: 'edit_id',
      originalIdColumn: 'original_id',
      statusColumn: 'status',
      checkerColumn: null,
      approverColumn: null,
      originalStatusValue: 'Under Editing',
      draftStatusValue: 'Sent to Checker'
    },
    geometry: {
      enabled: true,
      type: 'Point',
      column: 'shape',
      xField: 'xcoord',
      yField: 'ycoord'
    },
    insertFields: [
      'gid',
      'bridgeno',
      'asset_id',
      'distkm',
      'distm',
      'latitude',
      'longitude',
      'fdetail',
      'stnfrom',
      'stnto',
      'line',
      'xcoord',
      'ycoord',
      'railway',
      'division',
      'ersection',
      'tmssection',
      'state',
      'district',
      'remark',
      'date',
      'gisid',
      'valid',
      'user_type',
      'unit_type',
      'unit_code',
      'unit_name',
      'department',
      'user_id',
      'expired_flag',
      'mapped_flag',
      'mapped_id',
      'final_modified_by',
      'created_by',
      'bridgetype',
      'spanconf',
      'constituency',
      'gis_unique_id',
      'attachment_bundle_url'
    ],
    updateFields: [
      'gid',
      'bridgeno',
      'asset_id',
      'distkm',
      'distm',
      'latitude',
      'longitude',
      'fdetail',
      'stnfrom',
      'stnto',
      'line',
      'xcoord',
      'ycoord',
      'railway',
      'division',
      'ersection',
      'tmssection',
      'state',
      'district',
      'remark',
      'date',
      'gisid',
      'valid',
      'user_type',
      'unit_type',
      'unit_code',
      'unit_name',
      'department',
      'user_id',
      'expired_flag',
      'mapped_flag',
      'mapped_id',
      'final_modified_by',
      'created_by',
      'bridgetype',
      'spanconf',
      'constituency',
      'gis_unique_id',
      'attachment_bundle_url'
    ],
    searchableFields: [
      'bridgeno',
      'asset_id',
      'state',
      'district',
      'stnfrom',
      'stnto'
    ]
  },
  bridge_end: {
    table: 'sde.bridge_end',
    idColumn: 'objectid',
    idStrategy: 'manual',
    draftWorkflow: {
      table: 'sde.bridge_end_edit',
      editIdColumn: 'edit_id',
      originalIdColumn: 'original_id',
      statusColumn: 'status',
      checkerColumn: null,
      approverColumn: null,
      originalStatusValue: 'Under Editing',
      draftStatusValue: 'Sent to Checker'
    },
    geometry: {
      enabled: true,
      type: 'Point',
      column: 'shape',
      readColumn: 'geom',
      xField: 'xcoord',
      yField: 'ycoord'
    },
    insertFields: [
      'gid',
      'bridgeno',
      'asset_id',
      'distkm',
      'distm',
      'latitude',
      'longitude',
      'fdetail',
      'stnfrom',
      'stnto',
      'line',
      'xcoord',
      'ycoord',
      'railway',
      'division',
      'ersection',
      'tmssection',
      'state',
      'district',
      'remark',
      'date',
      'gisid',
      'valid',
      'user_type',
      'unit_type',
      'unit_code',
      'unit_name',
      'department',
      'user_id',
      'expired_flag',
      'mapped_flag',
      'mapped_id',
      'final_modified_by',
      'created_by',
      'bridgetype',
      'spanconf',
      'constituency',
      'gis_unique_id',
      'attachment_bundle_url'
    ],
    updateFields: [
      'gid',
      'bridgeno',
      'asset_id',
      'distkm',
      'distm',
      'latitude',
      'longitude',
      'fdetail',
      'stnfrom',
      'stnto',
      'line',
      'xcoord',
      'ycoord',
      'railway',
      'division',
      'ersection',
      'tmssection',
      'state',
      'district',
      'remark',
      'date',
      'gisid',
      'valid',
      'user_type',
      'unit_type',
      'unit_code',
      'unit_name',
      'department',
      'user_id',
      'expired_flag',
      'mapped_flag',
      'mapped_id',
      'final_modified_by',
      'created_by',
      'bridgetype',
      'spanconf',
      'constituency',
      'gis_unique_id',
      'attachment_bundle_url'
    ],
    searchableFields: [
      'bridgeno',
      'asset_id',
      'state',
      'district',
      'stnfrom',
      'stnto'
    ]
  },
  bridge_minor: {
    table: 'sde.bridge_minor',
    idColumn: 'objectid',
    idStrategy: 'manual',
    draftWorkflow: {
      table: 'sde.bridge_minor_edit',
      editIdColumn: 'edit_id',
      originalIdColumn: 'original_id',
      statusColumn: 'status',
      checkerColumn: null,
      approverColumn: null,
      originalStatusValue: 'Under Editing',
      draftStatusValue: 'Sent to Checker'
    },
    geometry: {
      enabled: true,
      type: 'Point',
      column: 'shape',
      readColumn: 'geom',
      xField: 'xcoord',
      yField: 'ycoord'
    },
    insertFields: [
      'gid',
      'bridgeno',
      'asset_id',
      'distkm',
      'distm',
      'latitude',
      'longitude',
      'fdetail',
      'stnfrom',
      'stnto',
      'line',
      'xcoord',
      'ycoord',
      'railway',
      'division',
      'ersection',
      'tmssection',
      'state',
      'district',
      'remark',
      'date',
      'gisid',
      'valid',
      'user_type',
      'unit_type',
      'unit_code',
      'unit_name',
      'department',
      'user_id',
      'expired_flag',
      'mapped_flag',
      'mapped_id',
      'final_modified_by',
      'created_by',
      'bridgetype',
      'spanconf',
      'constituency',
      'gis_unique_id',
      'attachment_bundle_url'
    ],
    updateFields: [
      'gid',
      'bridgeno',
      'asset_id',
      'distkm',
      'distm',
      'latitude',
      'longitude',
      'fdetail',
      'stnfrom',
      'stnto',
      'line',
      'xcoord',
      'ycoord',
      'railway',
      'division',
      'ersection',
      'tmssection',
      'state',
      'district',
      'remark',
      'date',
      'gisid',
      'valid',
      'user_type',
      'unit_type',
      'unit_code',
      'unit_name',
      'department',
      'user_id',
      'expired_flag',
      'mapped_flag',
      'mapped_id',
      'final_modified_by',
      'created_by',
      'bridgetype',
      'spanconf',
      'constituency',
      'gis_unique_id',
      'attachment_bundle_url'
    ],
    searchableFields: [
      'bridgeno',
      'asset_id',
      'state',
      'district',
      'stnfrom',
      'stnto'
    ]
  },

  landplan: buildLandPlanOnTrackLayerConfig(),
  landplan_ontrack: buildLandPlanOnTrackLayerConfig(),

  road_over_bridge: buildBridgeLikePointLayerConfig('road_over_bridge', 'robno'),
  rob: buildBridgeLikePointLayerConfig('road_over_bridge', 'robno'),
  rub_lhs: buildBridgeLikePointLayerConfig('rub_lhs', 'rubno'),
  ror: buildBridgeLikePointLayerConfig('ror', 'rorno'),
  levelxing: buildLevelXingLayerConfig(),
  level_xing: buildLevelXingLayerConfig(),
  pointxing: buildGenericPointLayerConfig('pointxing'),
  point_xing: buildGenericPointLayerConfig('pointxing'),
  switch_expansion_joint: buildGenericPointLayerConfig('switch_expansion_joint_1'),
  sej: buildGenericPointLayerConfig('switch_expansion_joint_1'),
  buffer_rails: buildGenericPointLayerConfig('buffer_rails')
};

