module.exports = {
  station: {
    table: 'sde.station',
    idColumn: 'objectid',
    idStrategy: 'manual', // manual MAX()+1 for now
    draftWorkflow: {
      table: 'sde.station_edit',
      editIdColumn: 'edit_id',
      originalIdColumn: 'original_id',
      statusColumn: 'status',
      checkerColumn: 'checkerdet',
      approverColumn: 'approverdet',
      originalStatusValue: 'Under Editing',
      draftStatusValue: 'Sent to Checker'
    },
    validation: {
      table: 'sde.station_1_code',
      idColumn: 'objectid',
      idStrategy: 'manual',
      insertFields: [
        'station_code',
        'station_valid_from',
        'station_valid_upto',
        'station_name',
        'zone_code',
        'division_code',
        'category'
      ]
    },

    geometry: {
      enabled: true,
      type: 'Point',
      column: 'shape',
      xField: 'xcoord',
      yField: 'ycoord'
    },

    insertFields: [
      'sttncode',
      'sttnname',
      'sttntype',
      'distkm',
      'distm',
      'state',
      'district',
      'constituncy',
      'latitude',
      'longitude',
      'xcoord',
      'ycoord',
      'railway',
      'category',
      'attachment_bundle_url'
    ],

    updateFields: [
      'distkm',
      'distm',
      'state',
      'district',
      'constituncy',
      'sttnname',
      'category',
      'sttntype',
      'attachment_bundle_url'
    ],

    searchableFields: [
      'sttncode',
      'state',
      'district'
    ]
  },
  bridge_start: {
    table: 'sde.bridge_start',
    idColumn: 'objectid',
    idStrategy: 'manual',
    draftWorkflow: {
      table: 'sde.bridge_start_edit',
      editIdColumn: 'edit_id',
      originalIdColumn: 'original_id',
      statusColumn: 'status',
      checkerColumn: null,
      approverColumn: null,
      originalStatusValue: 'Under Editing',
      draftStatusValue: 'Sent to Checker'
    },
    geometry: {
      enabled: true,
      type: 'Point',
      column: 'shape',
      xField: 'xcoord',
      yField: 'ycoord'
    },
    insertFields: [
      'gid',
      'bridgeno',
      'asset_id',
      'distkm',
      'distm',
      'latitude',
      'longitude',
      'fdetail',
      'stnfrom',
      'stnto',
      'line',
      'xcoord',
      'ycoord',
      'railway',
      'division',
      'ersection',
      'tmssection',
      'state',
      'district',
      'remark',
      'date',
      'gisid',
      'valid',
      'user_type',
      'unit_type',
      'unit_code',
      'unit_name',
      'department',
      'user_id',
      'expired_flag',
      'mapped_flag',
      'mapped_id',
      'final_modified_by',
      'created_by',
      'bridgetype',
      'spanconf',
      'constituncy',
      'gis_unique_id',
      'attachment_bundle_url'
    ],
    updateFields: [
      'gid',
      'bridgeno',
      'asset_id',
      'distkm',
      'distm',
      'latitude',
      'longitude',
      'fdetail',
      'stnfrom',
      'stnto',
      'line',
      'xcoord',
      'ycoord',
      'railway',
      'division',
      'ersection',
      'tmssection',
      'state',
      'district',
      'remark',
      'date',
      'gisid',
      'valid',
      'user_type',
      'unit_type',
      'unit_code',
      'unit_name',
      'department',
      'user_id',
      'expired_flag',
      'mapped_flag',
      'mapped_id',
      'final_modified_by',
      'created_by',
      'bridgetype',
      'spanconf',
      'constituncy',
      'gis_unique_id',
      'attachment_bundle_url'
    ],
    searchableFields: [
      'bridgeno',
      'asset_id',
      'state',
      'district',
      'stnfrom',
      'stnto'
    ]
  },
  bridge_end: {
    table: 'sde.bridge_end',
    idColumn: 'objectid',
    idStrategy: 'manual',
    draftWorkflow: {
      table: 'sde.bridge_end_edit',
      editIdColumn: 'edit_id',
      originalIdColumn: 'original_id',
      statusColumn: 'status',
      checkerColumn: null,
      approverColumn: null,
      originalStatusValue: 'Under Editing',
      draftStatusValue: 'Sent to Checker'
    },
    geometry: {
      enabled: true,
      type: 'Point',
      column: 'shape',
      xField: 'xcoord',
      yField: 'ycoord'
    },
    insertFields: [
      'gid',
      'bridgeno',
      'asset_id',
      'distkm',
      'distm',
      'latitude',
      'longitude',
      'fdetail',
      'stnfrom',
      'stnto',
      'line',
      'xcoord',
      'ycoord',
      'railway',
      'division',
      'ersection',
      'tmssection',
      'state',
      'district',
      'remark',
      'date',
      'gisid',
      'valid',
      'user_type',
      'unit_type',
      'unit_code',
      'unit_name',
      'department',
      'user_id',
      'expired_flag',
      'mapped_flag',
      'mapped_id',
      'final_modified_by',
      'created_by',
      'bridgetype',
      'spanconf',
      'constituncy',
      'gis_unique_id',
      'attachment_bundle_url'
    ],
    updateFields: [
      'gid',
      'bridgeno',
      'asset_id',
      'distkm',
      'distm',
      'latitude',
      'longitude',
      'fdetail',
      'stnfrom',
      'stnto',
      'line',
      'xcoord',
      'ycoord',
      'railway',
      'division',
      'ersection',
      'tmssection',
      'state',
      'district',
      'remark',
      'date',
      'gisid',
      'valid',
      'user_type',
      'unit_type',
      'unit_code',
      'unit_name',
      'department',
      'user_id',
      'expired_flag',
      'mapped_flag',
      'mapped_id',
      'final_modified_by',
      'created_by',
      'bridgetype',
      'spanconf',
      'constituncy',
      'gis_unique_id',
      'attachment_bundle_url'
    ],
    searchableFields: [
      'bridgeno',
      'asset_id',
      'state',
      'district',
      'stnfrom',
      'stnto'
    ]
  },
  bridge_minor: {
    table: 'sde.bridge_minor',
    idColumn: 'objectid',
    idStrategy: 'manual',
    draftWorkflow: {
      table: 'sde.bridge_minor_edit',
      editIdColumn: 'edit_id',
      originalIdColumn: 'original_id',
      statusColumn: 'status',
      checkerColumn: null,
      approverColumn: null,
      originalStatusValue: 'Under Editing',
      draftStatusValue: 'Sent to Checker'
    },
    geometry: {
      enabled: true,
      type: 'Point',
      column: 'shape',
      xField: 'xcoord',
      yField: 'ycoord'
    },
    insertFields: [
      'gid',
      'bridgeno',
      'asset_id',
      'distkm',
      'distm',
      'latitude',
      'longitude',
      'fdetail',
      'stnfrom',
      'stnto',
      'line',
      'xcoord',
      'ycoord',
      'railway',
      'division',
      'ersection',
      'tmssection',
      'state',
      'district',
      'remark',
      'date',
      'gisid',
      'valid',
      'user_type',
      'unit_type',
      'unit_code',
      'unit_name',
      'department',
      'user_id',
      'expired_flag',
      'mapped_flag',
      'mapped_id',
      'final_modified_by',
      'created_by',
      'bridgetype',
      'spanconf',
      'constituncy',
      'gis_unique_id',
      'attachment_bundle_url'
    ],
    updateFields: [
      'gid',
      'bridgeno',
      'asset_id',
      'distkm',
      'distm',
      'latitude',
      'longitude',
      'fdetail',
      'stnfrom',
      'stnto',
      'line',
      'xcoord',
      'ycoord',
      'railway',
      'division',
      'ersection',
      'tmssection',
      'state',
      'district',
      'remark',
      'date',
      'gisid',
      'valid',
      'user_type',
      'unit_type',
      'unit_code',
      'unit_name',
      'department',
      'user_id',
      'expired_flag',
      'mapped_flag',
      'mapped_id',
      'final_modified_by',
      'created_by',
      'bridgetype',
      'spanconf',
      'constituncy',
      'gis_unique_id',
      'attachment_bundle_url'
    ],
    searchableFields: [
      'bridgeno',
      'asset_id',
      'state',
      'district',
      'stnfrom',
      'stnto'
    ]
  }
};

